<div id="workshop">
	<div id="content">
			<div id="banner"><!--  --></div>
		<div id="column1">
			<div id="title"><h1 class="textReplace">Workshop</h1></div>
			<div class="clearAll"><!--  --></div>
			<p>Fed up of going to the same place, doing the same thing every time you celebrate a special occassion? We may just have the solution for you... have a go at a Hunkydory Workshop! Ideal for <strong>birthday parties, hen parties or work events</strong> suitable for all ages!</p>
			<p>The workshop involves <strong>decorating 6 cupcakes and 2 Love Pops</strong>:<br />&middot; Instruction and help from Anna (Hunkydory Cakes' cake maker).<br />&middot; Piping with a selection of different nozzles.<br />&middot; Learning how to work with sugar paste to create your own designs.<br />&middot; Experimenting to create your own wonderful cupcake flavours.<br />&middot; A worksheet of recipes and handy tips so that you don't need to take any notes during the workshop.<br />&middot; Using melted coloured chocolate and your own handmade sugar decorations to make your Love Pops.<br />&middot; Funky packaging in which to take your bespoke creations home, that gives them the professional finish they deserve.<br />&middot; A lot of fun and giggles!<br />&middot; A disc of photographs from the workshop.</p>
			<p>Hunkydory Workshops will come to your home/office/chosen location so you don't need to organise transport or lifts. Workshops last around 2 and a half hours. If you live in Sheffield, Chesterfield or the local area why not give it a try!</p>
			<p>Hunkydory will provide everything needed so you really do not have to lift a finger.</p>
			<p><strong>A Hunkydory Workshop is a great party idea!</strong> But don't just take our word for it, please take a look at our <a href="<?php echo $this->url(array(), 'testimonials') ?>">testimonials</a> and visit us on <a href="http://www.facebook.com/pages/Hunkydory-Cakes/140420469351784">Facebook</a> to see some of the wonderful creations past parties have created at a Hunkydory Workshop.</p>			 
			<h2>Packages</h2>
			<p><strong>Groups of 4+:<br />Hunkydory Workshop - &pound;24 per person.</strong></p>
			<p><strong>Why not make a day of it and combine this with a <a href="<?php echo $this->url(array(), 'tea-party') ?>">Hunkydory Tea Party</a>?<br />Hunkydory Tea Party &amp; Workshop</strong> (typically around 4 &amp; a half hours)<br /><strong>- &pound;44 per person - including Standard Tea Party<br />- &pound;48 per person - incliding Deluxe Tea Party.</strong></p>
			<h2>How to book your workshop</h2>
			<p>Please don't hesitate to contact Anna for more information regarding <strong>booking a Hunkydory Workshop</strong>, give her a call on <strong>0114 266 4573</strong> or email her at <a href="mailto:enquiries@hunkydorycakes.co.uk"><strong>enquiries@hunkydorycakes.co.uk</strong></a>.</p>
			<div class="clearAll"><!--  --></div>
			<div id="return-home"><a href="/"><img src="/images/return-homepage.gif" height="13" width="260" alt="Return to the homepage" /></a></div>
		</div>
		<div id="column2">
			<div id="background"><!--  --></div>
			<div class="clearAll"><!--  --></div>
		</div>
	</div>
</div>