<div id="party-cakes">
	<div id="content">
		<div id="banner"><a href="<?php echo $this->url(array(), 'party-cakes-gallery') ?>" id="banner-enter-gallery"><img src="/images/enter-gallery-green.gif" width="203" height="19" alt="Enter Gallery" /></a></div>
		<div id="title"><h1 class="textReplace">Party Cakes</h1></div>
		<div id="enter-gallery"><a href="<?php echo $this->url(array(), 'party-cakes-gallery')?>"><img src="/images/enter-gallery.gif" height="15" width="218" alt="Enter Gallery" /></a></div>
		<div class="clearAll"><!--  --></div>
		<p>HUNKYDORY cake designer Anna Williams has a passion for creating fashionable party cakes to customers in Sheffield and the surrounding areas. Combining the finest ingredients with couture design to produce inspiring, decadent cake creations. Hunkydory Cakes aim to provide the dream cake for any special occasion!</p>
		<div class="clearAll"><!--  --></div>
		<div id="return-home" class="textReplace">Return to the homepage</div>
	</div>
</div>