<div id="basic-cakes">
	<div id="content">
		<div id="banner"><a href="<?php echo $this->url(array(), 'basic-cakes-gallery') ?>" id="banner-enter-gallery"><img src="/images/enter-gallery-green.gif" width="203" height="19" alt="Enter Gallery" /></a></div>
		<div id="title"><h1 class="textReplace">Basic Cakes</h1></div>
		<div id="enter-gallery"><a href="<?php echo $this->url(array(), 'basic-cakes-gallery')?>"><img src="/images/enter-gallery.gif" height="15" width="218" alt="Enter Gallery" /></a></div>
		<div class="clearAll"><!--  --></div>
		<p>Hunkydory Cakes Basics range has been designed to help make your life a little bit easier. This range offers a selection of inexpensive delicious cakes. If you can't find what you are after give us a call on 0114 266 4573 or email <a href="mailto:enquiries@hunkydorycakes.co.uk">enquiries@hunkydorycakes.co.uk</a> and request the cake you are wanting. We are happy to negotiate on prices for larger orders.</p>
		<div class="clearAll"><!--  --></div>
		<div id="return-home" class="textReplace">Return to the homepage</div>
	</div>
</div>