<div id="making-an-order">
	<div id="content">
		<div id="title"><h1 class="textReplace">Making an Order</h1></div>
		<div class="clearAll"><!--  --></div>
		<p><strong>Where is Hunkydory Cakes located?</strong><br />126 Blair Athol Road, Sheffield S11 7GD. Hunkydory cakes is just off Ecclesall Road South in Sheffield.</p>
		<p><strong>Can I collect my cake?</strong><br />Yes, orders can be collected from 126 Blair Athol Road, Sheffield S11 7GD.</p>
		<p><strong>What are Hunkydory Cakes collection times?</strong><br />Standard collection hours are Monday - Friday 11am-7pm &amp; Saturdays &amp; Sunday 9am-12pm.</p>
		<p><strong>Do Hunkydory Cakes deliver?</strong><br />Yes, we deliver all cakes &amp; cupcakes by hand within Sheffield, Chesterfield &amp; the surrounding area. Orders are subject to a &pound;10 delivery charge to Sheffield postcodes. Postcodes outside of Sheffield may be subject to a larger delivery charge, please call or email us your address and we will provide you with an estimated cost.</p>
		<p><strong>How far in advance do I need to place my order?</strong><br />The more notice given the more likely it is that we will be able to accommodate your order.<br />Cupcake &amp; Hunkydory Basic orders require 3 working days notice.<br />The majority of Party, Children's, Anniversary &amp; Christening cake orders should be placed at least 3 working days in advance.<br />Corporate &amp; Photo cakes orders should be placed at least 6 working days in advance.<br />Please refer to the cake page to confirm the number of days notice required.</p>
		<p>For larger orders such as Wedding cakes, it is always best to confirm a booking as soon as you're sure (we need a 25% deposit to confirm large orders with the remainder payable 4 weeks prior to the order date). Please give us a call on 0114 266 4573 or email <a href="mailto:enquiries@hunkydorycakes.co.uk">enquiries@hunkydorycakes.co.uk</a> to arrange an appointment.</p>
		<div class="clearAll"><!--  --></div>
		<div id="return-home"><a href="/"><img src="/images/return-homepage.gif" height="13" width="260" alt="Return to the homepage" /></a></div>
	</div>
</div>