<div id="about-us">
	<div id="content">
		<div id="title"><h1 class="textReplace">About Us</h1></div>
		<div class="clearAll"><!--  --></div>
		<img src="/images/about-us-model.gif" width="302" height="352" alt="Anna Williams - Hunkydory Cakes" align="left" id="mainImage" />
		<p>Wedding cake designer Anna Williams established Hunkydory Cakes in 2011. Anna has always had a flair for art and design, this was developed at The Glasgow School where she did a degree in Graphic Desgn. <br />Another great love of Anna's is cooking and in paticular baking... these two ingredients naturally led her into the art of cake making.</p>
		<p>Influences come from her grandmother hailed 'The Queen of Cakes' and her Mum for teaching her that cooking great tasting food requires good quality ingredients and no short cuts.</p>
		<p>Anna considers every cake creation to be a work of art and always makes sure that her cakes taste beautiful too. Spending time in sourcing the best quality ingredients and baking cakes in very small batches is her key to taste success.</p>
		<p>Hunkydory Cakes is about offering people a bespoke service, Anna takes time to understand exactly what it is the customer has in mind so that they then have the cake of their dreams!</p>
		<div class="clearAll"><!--  --></div>
		<div id="return-home" class="textReplace">Return to the homepage</div>
	</div>
</div>