<div id="anniversary-cakes-gallery">
	<div id="content">
		<div id="bespoke"><p class="textReplace">Not what you're after? We can create a bespoke cake! Drop us an email or give us a call.</p></div>
		<div id="title"><h1 class="textReplace">Anniversary Gallery</h1></div>
		<div id="further_info"><h2 class="textReplace">Please click on the cake for further information &amp; prices.</h2></div>
		<div class="clearAll"><!--  --></div>
		<ol id="gallery">
			<?php /* Deleted 26th Feb 2012 ?><li class="r1 c1"><a href="<?php echo $this->url(array(), 'lilies-and-daisies-cake') ?>"><span>lilies &amp; daisies</span></a></li><?php */ ?>
			<li class="r1 c1"><a href="<?php echo $this->url(array(), 'lily-spray-cake') ?>"><span>lily spray</span></a></li>
			<?php /* Deleted 26th Feb 2012 ?><li class="r1 c3"><a href="<?php echo $this->url(array(), 'ring-a-roses-cake') ?>"><span>ring-a-roses</span></a></li><?php */ ?>
			<li class="r1 c2"><a href="<?php echo $this->url(array(), 'heart-cake') ?>"><span>anniversary heart</span></a></li>
			<li class="r1 c3"><a href="<?php echo $this->url(array(), 'rose-cake') ?>"><span>anniversary rose</span></a></li>
			<li class="r1 c4"><span>Watch this space!</span></li>
			<li class="r1 c5"><span>Watch this space!</span></li>
		</ol>
		<div class="clearAll"><!--  --></div>
		<div id="things-to-know"><a href="<?php echo $this->url(array(), 'making-an-order') ?>"><img src="/images/things-to-know-order.gif" alt="Things to know when making an order" /></a></div>
		<div id="return-home"><a href="<?php echo $this->url(array(), 'anniversary-cakes')?>"><img src="/images/return-homepage.gif" alt="Return to the homepage" /></a></div>
	</div>
</div>