<div id="anniversary-cakes">
	<div id="content">
		<div id="banner"><a href="<?php echo $this->url(array(), 'anniversary-cakes-gallery') ?>" id="banner-enter-gallery"><img src="/images/enter-gallery-green.gif" width="203" height="19" alt="Enter Gallery" /></a></div>
		<div id="title"><h1 class="textReplace">Wedding Cakes</h1></div>
		<div id="enter-gallery"><a href="<?php echo $this->url(array(), 'anniversary-cakes-gallery')?>"><img src="/images/enter-gallery.gif" height="15" width="218" alt="Enter Gallery" /></a></div>
		<div class="clearAll"><!--  --></div>
		<p>Anniversary Cakes are becoming ever more popular; this is a great way to show your loved one how much you care. If you can't find what you are after then give us a call on 0114 266 4573 or email <a href="mailto:enquiries@hunkydorycakes.co.uk">enquiries@hunkydorycakes.co.uk</a> to arrange designing a bespoke cake for the day!</p>
		<div class="clearAll"><!--  --></div>
		<div id="return-home" class="textReplace">Return to the homepage</div>
	</div>
</div>