<div id="wedding-cakes">
	<div id="content">
		<div id="banner"><a href="<?php echo $this->url(array(), 'wedding-cakes-gallery') ?>" id="banner-enter-gallery"><img src="/images/enter-gallery-green.gif" width="203" height="19" alt="Enter Gallery" /></a></div>
		<div id="title"><h1 class="textReplace">Wedding Cakes</h1></div>
		<div id="enter-gallery"><a href="<?php echo $this->url(array(), 'wedding-cakes-gallery')?>"><img src="/images/enter-gallery.gif" height="15" width="218" alt="Enter Gallery" /></a></div>
		<div class="clearAll"><!--  --></div>
		<p>Make one of the most special days of your life even more memorable with a Hunkydory Wedding Cake. Choose an existing cake from our gallery, or arrange an appointment to discuss a bespoke creation! Included in the price is delivery within Sheffield and the surrounding areas and assembling the cake at your venue.</p>
		<div class="clearAll"><!--  --></div>
		<div id="return-home" class="textReplace">Return to the homepage</div>
	</div>
</div>