<div id="christening-cakes-gallery">
	<div id="content">
		<div id="bespoke"><p class="textReplace">Not what you're after? We can create a bespoke cake! Drop us an email or give us a call.</p></div>
		<div id="title"><h1 class="textReplace">Christening Cakes Gallery</h1></div>
		<div id="further_info"><h2 class="textReplace">Please click on the cake for further information &amp; prices.</h2></div>
		<div class="clearAll"><!--  --></div>
		<ol id="gallery">
			<li class="r1 c1"><a href="<?php echo $this->url(array(), 'pretty-in-pink-cake') ?>"><span>pretty in pink!</span></a></li>
			<li class="r1 c2"><a href="<?php echo $this->url(array(), 'baby-blue-cake') ?>"><span>baby blue</span></a></li>
			<li class="r1 c3"><a href="<?php echo $this->url(array(), 'blossom-and-daisies-cake') ?>"><span>blossom &amp; daisies</span></a></li>
			<li class="r1 c4"><a href="<?php echo $this->url(array(), 'christening-bird') ?>"><span>bird</span></a></li>
			<li class="r1 c5"><a href="<?php echo $this->url(array(), 'christening-jungle') ?>"><span>jungle</span></a></li>
			<li class="r2 c1"><a href="<?php echo $this->url(array(), 'christening-vintage-rose') ?>"><span>vintage rose</span></a></li>
			<li class="r2 c2"><span>watch this space!</span></li>
			<li class="r2 c3"><span>watch this space!</span></li>
			<li class="r2 c4"><span>watch this space!</span></li>
			<li class="r2 c5"><span>watch this space!</span></li>
			</ol>
		<div class="clearAll"><!--  --></div>
		<div id="things-to-know"><a href="<?php echo $this->url(array(), 'making-an-order') ?>"><img src="/images/things-to-know-order.gif" alt="Things to know when making an order" /></a></div>
		<div id="return-home"><a href="<?php echo $this->url(array(), 'christening-cakes')?>"><img src="/images/return-homepage.gif" alt="Return to the homepage" /></a></div>
	</div>
</div>