<div id="childrens-cakes">
	<div id="content">
		<div id="banner"><a href="<?php echo $this->url(array(), 'childrens-cakes-gallery') ?>" id="banner-enter-gallery"><img src="/images/enter-gallery-green.gif" width="203" height="19" alt="Enter Gallery" /></a></div>
		<div id="title"><h1 class="textReplace">Children's Cakes</h1></div>
		<div id="enter-gallery"><a href="<?php echo $this->url(array(), 'childrens-cakes-gallery')?>"><img src="/images/enter-gallery.gif" height="15" width="218" alt="Enter Gallery" /></a></div>
		<div class="clearAll"><!--  --></div>
		<p>Hunkydory Cakes love making cakes for children. Capture their imagination by creating a cake of their favourite toy, fictional character or football team. This is guaranteed to put a smile on their face! If you can't find the cake you are after in the gallery then give us a call on 0114 266 4573 or email <a href="mailto:enquiries@hunkydorycakes.co.uk">enquiries@hunkydorycakes.co.uk</a> to arrange designing a bespoke cake!</p>
		<div class="clearAll"><!--  --></div>
		<div id="return-home" class="textReplace">Return to the homepage</div>
	</div>
</div>