<div id="fillings-and-flavours">
	<div id="content">
		<div id="cake-portions-title"><h1 class="textReplace">Cake Portions</h1></div>
		<p class="clearAll">Decided on the cake?  How many people will it serve? Work out the correct size cake/number of tiers to choose from the portions table below.  The portions table gives a reliable estimate of how many portions can be served from a given size of cake. The portions table should help you in picking the right size of wedding cake or large cake for your special occasion.</p>
		<div class="table-top"></div>
		<table id="portions" cellspacing="0" cellpadding="0">
			<thead>
				<tr>
					<td colspan="6" class="r1">&nbsp;</td>
				</tr>
				<tr class="r2">
					<th>Tiered Wedding Cakes</th>
					<th>Circular Sponge</th>
					<th>Square Sponge</th>
					<th>Fruit Round</th>
					<th>Fruit Square</th>
					<th>Dessert Portions</th>
				</tr>
				<tr>
					<td colspan="6" class="r3">&nbsp;</td>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<td colspan="6">Portion servings are based on sponge cake cut at 2&quot; x 1&quot; portions. fruit cake cut at 1&quot; square portions</td>
				</tr>
			</tfoot>
			<tbody>
				<tr class="r1">
					<td class="c1">Three Tiers: 6&quot;, 8&quot;, 10&quot;</td>
					<td class="c2">72</td>
					<td class="c3">95</td>
					<td class="c4">120</td>
					<td class="c5">155</td>
					<td class="c6">50</td>
				</tr>
				<tr class="r2">
					<td class="c1">Three Tiers: 8&quot;, 10&quot;, 12&quot;</td>
					<td class="c2">120</td>
					<td class="c3">145</td>
					<td class="c4">180</td>
					<td class="c5">240</td>
					<td class="c6">75</td>
				</tr>
				<tr class="r3">
					<td class="c1">Four Tiers: 6&quot;, 8&quot;, 10&quot;, 12&quot;</td>
					<td class="c2">132</td>
					<td class="c3">180</td>
					<td class="c4">200</td>
					<td class="c5">265</td>
					<td class="c6">85</td>
				</tr>
				<tr class="r4">
					<td class="c1">Four Tiers: 8&quot;, 10&quot;, 12&quot;, 14&quot;</td>
					<td class="c2">212</td>
					<td class="c3">260</td>
					<td class="c4">300</td>
					<td class="c5">395</td>
					<td class="c6">130</td>
				</tr>
			</tbody>
		</table>
		<div class="table-bottom"></div>
		<div class="clearAll"><!--  --></div>
		<div id="fillings-and-flavours-title"><h1 class="textReplace">Fillings and Flavours</h1></div>
		<div class="clearAll"><!--  --></div>
		<p>Hunkydory Cakes are made fresh to order. We endeavour to use the finest quality of ingredients available, including free range eggs.  Hunkydory Cakes believe that good ingredients and a true love of cake making are essential to producing outstanding cakes.</p>
		<div class="table-top"></div>
		<table id="fillings" cellspacing="0" cellpadding="0">
			<thead>
				<tr>
					<td colspan="3" class="r1">&nbsp;</td>
				</tr>
				<tr class="r2">
					<th>Cake Flavours</th>
					<th>Preserves and Curds</th>
					<th>Buttercream Fillings</th>
				</tr>
				<tr>
					<td colspan="3" class="r3">&nbsp;</td>
				</tr>
			</thead>
			<tbody>
				<tr class="r1">
					<td class="c1">Classic Vanilla</td>
					<td class="c2">Strawberry Preserve</td>
					<td class="c3">Vanilla</td>
				</tr>
				<tr class="r2">
					<td class="c1">Indulgant Chocolate</td>
					<td class="c2">Rasperry Preserve</td>
					<td class="c3">Chocolate Ganache</td>
				</tr>
				<tr class="r3">
					<td class="c1">Espresso Coffee</td>
					<td class="c2">Apricot Preserve</td>
					<td class="c3">Espresso Coffee</td>
				</tr>
				<tr class="r4">
					<td class="c1">Fruit Cake</td>
					<td class="c2">Ginger Preserve</td>
					<td class="c3">Mocha</td>
				</tr>
				<tr class="r5">
					<td class="c1">Lemon Zest</td>
					<td class="c2">Peach Preserve</td>
					<td class="c3">Orange</td>
				</tr>
				<tr class="r6">
					<td class="c1">Orange Zest</td>
					<td class="c2">Blackcurrant Preserve</td>
					<td class="c3">Chocolate and Orange Zest</td>
				</tr>
				<tr class="r7">
					<td class="c1">Banana</td>
					<td class="c2">Lemon Curd</td>
					<td class="c3">Lemon</td>
				</tr>
				<tr class="r8">
					<td class="c1">Red Velvet</td>
					<td class="c2">&nbsp;</td>
					<td class="c3">Coconut</td>
				</tr>
			</tbody>
		</table>
		<div class="table-bottom"></div>
		<div class="clearAll"><!--  --></div>
		<p>Hunkydory advise that cakes made up of three tiers or more have a fruit cake base to ensure stability.</p>
		<div class="clearAll"><!--  --></div>
		
		<div id="return-home" class="textReplace">Return to the homepage</div>
		<div class="clearAll"><!--  --></div>
	</div>
</div>