<div id="favours-gallery">
	<div id="content">
		<div id="bespoke"><p class="textReplace">Not what you're after? We can create a bespoke cake! Drop us an email or give us a call.</p></div>
		<div id="title"><h1 class="textReplace">Favours Gallery</h1></div>
		<div id="further_info"><h2 class="textReplace">Please click on the cake for further information &amp; prices.</h2></div>
		<div class="clearAll"><!--  --></div>
		<ol id="gallery">
			<li class="r1 c1"><a href="<?php echo $this->url(array(), 'wedding-dress-no1-favour') ?>"><span>wedding dress no.1</span></a></li>
			<li class="r1 c2"><a href="<?php echo $this->url(array(), 'wedding-dress-no2-favour') ?>"><span>wedding dress no.2</span></a></li>
			<li class="r1 c3"><a href="<?php echo $this->url(array(), 'white-doves-favour') ?>"><span>white doves no.1</span></a></li>
			<li class="r1 c4"><a href="<?php echo $this->url(array(), 'white-doves-favour') ?>"><span>white doves no.2</span></a></li>
			<li class="r1 c5"><a href="<?php echo $this->url(array(), 'red-rose-favour') ?>"><span>red rose</span></a></li>
			<li class="r2 c1"><a href="<?php echo $this->url(array(), 'gingham-heart-favour') ?>"><span>gingham heart</span></a></li>
			<li class="r2 c2"><a href="<?php echo $this->url(array(), 'dots-of-love-favour') ?>"><span>dots of love</span></a></li>
			<li class="r2 c3"><a href="<?php echo $this->url(array(), 'peace-and-love-favour') ?>"><span>peace &amp; love</span></a></li>
			<li class="r2 c4"><span>Watch this space!</span></li>
			<li class="r2 c5"><span>Watch this space!</span></li>
		</ol>
		<div class="clearAll"><!--  --></div>
		<div id="things-to-know"><a href="<?php echo $this->url(array(), 'making-an-order') ?>"><img src="/images/things-to-know-order.gif" alt="Things to know when making an order" /></a></div>
		<div id="return-home"><a href="<?php echo $this->url(array(), 'favours')?>"><img src="/images/return-homepage.gif" alt="Return to the homepage" /></a></div>
	</div>
</div>