<div id="contact">
	<div id="content">
		<div id="title"><h1 class="textReplace">Contact</h1></div>
		<div class="clearAll"><!--  --></div>
		<div id="map">
			<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=126+blair+athol+road,+s11+7gd&amp;aq=&amp;sll=53.800651,-4.064941&amp;sspn=15.581897,46.538086&amp;ie=UTF8&amp;hq=&amp;hnear=126+Blair+Athol+Rd,+Sheffield,+South+Yorkshire+S11+7GD,+United+Kingdom&amp;t=h&amp;z=14&amp;ll=53.361298,-1.509416&amp;output=embed"></iframe><br /><small><a href="http://maps.google.co.uk/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=126+blair+athol+road,+s11+7gd&amp;aq=&amp;sll=53.800651,-4.064941&amp;sspn=15.581897,46.538086&amp;ie=UTF8&amp;hq=&amp;hnear=126+Blair+Athol+Rd,+Sheffield,+South+Yorkshire+S11+7GD,+United+Kingdom&amp;t=h&amp;z=14&amp;ll=53.361298,-1.509416" style="color:#0000FF;text-align:left">View Larger Map</a></small>
		</div>
		<h2 class="blue">Sheffield Cake &amp; Cupcake Makers</h2>
		<p>Email us: enquiries@hunkydorycakes.co.uk</p>
		<p>Tel: 0114 266 4573<br />Mob: 07922 92 33 64</p>
		<p>Hunkydory is located at:<br />126 Blair Athol Road, Sheffield S11 7GD.</p>
		<p>Standard Collection Hours are: <br />Monday - Friday 11am-7pm<br />Saturdays &amp; Sundays 9am-12pm.</p>
		<div class="clearAll"><!--  --></div>
		<div id="return-home"><a href="/"><img src="/images/return-homepage.gif" height="13" width="260" alt="Return to the homepage" /></a></div>
	</div>
</div>