<div id="cupcakes">
	<div id="content">
		<div id="banner"><a href="<?php echo $this->url(array(), 'cupcakes-gallery') ?>" id="banner-enter-gallery"><img src="/images/enter-gallery-green.gif" width="203" height="19" alt="Enter Gallery" /></a></div>
		<div id="title"><h1 class="textReplace">Wedding Cakes</h1></div>
		<div id="enter-gallery"><a href="<?php echo $this->url(array(), 'cupcakes-gallery')?>"><img src="/images/enter-gallery.gif" height="15" width="218" alt="Enter Gallery" /></a></div>
		<div class="clearAll"><!--  --></div>
		<p>HUNKYDORY loves Cupcakes! We want you to love our Cupcakes, so if you can't find the flavour you are after drop us a line and we will do our best to please you. Our Cupcakes are all made fresh to order guaranteeing a beautiful moist fresh sponge with delicious frosting. We deliver within Sheffield and the surrounding areas. Give us a call on 0114 266 4573 or email us on <a href="mailto:enquiries@hunkydorycakes.co.uk">enquiries@hunkydorycakes.co.uk</a></p>
		<div class="clearAll"><!--  --></div>
		<div id="return-home" class="textReplace">Return to the homepage</div>
	</div>
</div>